export const SITE_CONFIG = {
  brand: {
    name: 'QYVORA',
    description:
      'Building a strong cybersecurity ecosystem in Africa.',
    siteUrl: 'https://qyvora.netlify.app',
  },
  contact: {
    opsEmail: 'qyvorasec@gmail.com',
    securityDeskEmail: 'qyvorasec@gmail.com',
    whatsappUrl: 'https://chat.whatsapp.com/Ja8pR0FZQAI2pceGjQpji5',
    whatsappLabel: 'https://chat.whatsapp.com/Ja8pR0FZQAI2pceGjQpji5',
    headquarters: 'Remote',
    responseTime: 'within 24 hours',
  },
  contactPage: {
    heroTag: '// TRANSMISSION',
    heroTitle: 'Contact the Desk',
    heroSubtitle: 'Establishing a secure channel for inquiries, partnerships, and operational support.',
    emailHeading: 'Email Intelligence',
    emailDescription: 'Direct secure channel to our operations desk.',
    whatsappHeading: 'Website',
    whatsappDescription: 'Primary public platform URL.',
    hqHeading: 'Operations',
    hqDescriptionSuffix: 'Netlify-hosted infrastructure.',
    formTitle: 'Secure Message Form',
    sentTitle: 'Transmission Received',
    sentButtonLabel: 'Send Another',
    selectSubjectPlaceholder: 'Select Mission Type',
    errorPrefix: 'Transmission failed. Try emailing us directly at',
    submitLabel: 'Send Transmission',
    sendingLabel: 'Sending...',
    labels: {
      name: 'Name',
      email: 'Email',
      subject: 'Subject',
      message: 'Message',
    },
    placeholders: {
      name: 'Alhassan Boateng',
      email: 'operations@yourcompany.africa',
      message: 'Encrypted transmission here...',
    },
  },
  social: [
    {
      key: 'x',
      label: 'Follow on X',
      handle: '@qyvorasec',
      desc: 'Real-time ops, advisories, and updates.',
      href: 'https://x.com/qyvorasec',
      action: 'Follow',
    },
    {
      key: 'linkedin',
      label: 'Connect on LinkedIn',
      handle: 'QYVORA',
      desc: 'Company updates and operator wins.',
      href: 'https://linkedin.com/company/qyvora',
      action: 'Connect',
    },
    {
      key: 'github',
      label: 'View on GitHub',
      handle: 'QYVORA',
      desc: 'Open source tools, platform code, and public engineering updates.',
      href: 'https://github.com/QYVORA',
      action: 'View',
    },
    {
      key: 'youtube',
      label: 'Watch on YouTube',
      handle: '@QYVORA',
      desc: 'Tutorials, walkthroughs, and operator content.',
      href: 'https://www.youtube.com/@QYVORA',
      action: 'Subscribe',
    },
    {
      key: 'medium',
      label: 'Read on Medium',
      handle: '@qyvorasec',
      desc: 'Write-ups, research notes, and field reports.',
      href: 'https://medium.com/@qyvorasec',
      action: 'Read',
    },
    {
      key: 'whatsapp',
      label: 'Join on WhatsApp',
      handle: 'QYVORA Community',
      desc: 'Live sessions, announcements, and operator comms.',
      href: 'https://chat.whatsapp.com/Ja8pR0FZQAI2pceGjQpji5',
      action: 'Join',
    },
  ],
  nav: {
    groups: [
      {
        key: 'learning',
        label: 'Learning',
        items: [
          { key: 'courses', label: 'Courses', path: '/courses', desc: 'Security courses' },
          { key: 'bootcamp', label: 'Bootcamp', path: '/hpb', desc: 'Hacker Protocol Bootcamp' },
          { key: 'labs', label: 'Labs', path: '/labs', desc: 'Attack labs' },
          { key: 'cp', label: 'Cyber Coin', path: '/cp', desc: 'CP reward system' },
          { key: 'simulations', label: 'Simulations', path: '/simulations', desc: 'Live tool demos' },
          { key: 'blogs', label: 'Blogs', path: '/blogs', desc: 'Security articles' },
        ],
      },
      {
        key: 'community',
        label: 'Community',
        items: [
          { key: 'leaderboard', label: 'Leaderboard', path: '/leaderboard', desc: 'Top operators ranking' },
          { key: 'market', label: 'Market', path: '/zero-day-market', desc: 'Zero-day vulnerability market' },
        ],
      },
      {
        key: 'company',
        label: 'Company',
        items: [
          { key: 'team', label: 'Team', path: '/team', desc: 'Our team' },
          { key: 'quiteroot', label: 'QuiteRoot', path: '/quiteroot', desc: 'Our offensive research collective' },
          { key: 'terms', label: 'Terms of Service', path: '/terms', desc: 'Terms of Service' },
        ],
      },
      {
        key: 'platform',
        label: 'Platform',
        items: [
          { key: 'anansi', label: 'Anansi', path: '/anansi', desc: 'Attack Surface Intelligence' },
          { key: 'toha3ee', label: 'Toha3ee', path: '/toha3ee', desc: 'Local & network security assessment framework' },
          { key: 'jabari', label: 'Jabari', path: '/jabari', desc: 'Android security assessment' },
          { key: 'aksum', label: 'Aksum', path: '/aksum', desc: 'Binary security assessment & reverse engineering' },
          { key: 'services', label: 'Services', path: '/services', desc: 'Enterprise security services' },
        ],
      },
    ],
    platform: [
      { key: 'services', label: 'Services', path: '/services', desc: 'Enterprise security services' },
      { key: 'courses', label: 'Courses', path: '/courses', desc: 'Security courses' },
      { key: 'bootcamp', label: 'Bootcamp', path: '/hpb', desc: 'Hacker Protocol Bootcamp' },
      { key: 'labs', label: 'Labs', path: '/labs', desc: 'Attack labs' },
      { key: 'simulations', label: 'Simulations', path: '/simulations', desc: 'Live tool demos' },
      { key: 'anansi', label: 'Anansi', path: '/anansi', desc: 'Attack Surface Intelligence' },
      { key: 'jabari', label: 'Jabari', path: '/jabari', desc: 'Android security assessment' },
      { key: 'aksum', label: 'Aksum', path: '/aksum', desc: 'Binary security assessment & reverse engineering' },
      { key: 'leaderboard', label: 'Leaderboard', path: '/leaderboard', desc: 'Top operators ranking' },
    ],
    company: [
      { key: 'team', label: 'Team', path: '/team', desc: 'Our team' },
      { key: 'contact', label: 'Contact', path: '/contact', desc: 'Open secure contact modal', modal: true }
    ],
  },
  
  footer: {
    links: [
      { label: 'Terms of Service', path: '/terms' },
      { label: 'Courses', path: '/courses' },
      { label: 'Bootcamp', path: '/hpb' },
      { label: 'Labs', path: '/labs' },
    ],
  },
} as const;
