export const SITE_CONFIG = {
  brand: {
    name: 'QYVORA',
    description:
      'Building a strong cybersecurity ecosystem in Africa.',
    siteUrl: 'https://qyvora.netlify.app',
  },
  contact: {
    opsEmail: 'ops@qyvora.netlify.app',
    securityDeskEmail: 'ops@qyvora.netlify.app',
    whatsappUrl: 'https://chat.whatsapp.com/Ja8pR0FZQAI2pceGjQpji5',
    whatsappLabel: 'https://chat.whatsapp.com/Ja8pR0FZQAI2pceGjQpji5',
    headquarters: 'Remote',
    responseTime: 'within 24 hours',
  },
  contactPage: {
    heroTag: '// TRANSMISSION',
    heroTitle: 'Contact the Desk',
    heroSubtitle: 'Establishing a secure channel for inquiries, partnerships, and operational support.',
    emailHeading: 'Email Intelligence',
    emailDescription: 'Direct secure channel to our operations desk.',
    whatsappHeading: 'Website',
    whatsappDescription: 'Primary public platform URL.',
    hqHeading: 'Operations',
    hqDescriptionSuffix: 'Netlify-hosted infrastructure.',
    formTitle: 'Secure Message Form',
    sentTitle: 'Transmission Received',
    sentButtonLabel: 'Send Another',
    selectSubjectPlaceholder: 'Select Mission Type',
    errorPrefix: 'Transmission failed. Try emailing us directly at',
    submitLabel: 'Send Transmission',
    sendingLabel: 'Sending...',
    labels: {
      name: 'Name',
      email: 'Email',
      subject: 'Subject',
      message: 'Message',
    },
    placeholders: {
      name: 'Alhassan Boateng',
      email: 'operations@yourcompany.africa',
      message: 'Encrypted transmission here...',
    },
  },
  social: [
    {
      key: 'x',
      label: 'Follow on X',
      handle: '@sethabbey328208',
      desc: 'Real-time ops, advisories, and updates.',
      href: 'https://x.com/sethabbey328208',
      action: 'Follow',
    },
    {
      key: 'linkedin',
      label: 'Connect on LinkedIn',
      handle: 'QYVORA',
      desc: 'Company updates and operator wins.',
      href: 'https://www.linkedin.com/company/qyvora/',
      action: 'Connect',
    },
    {
      key: 'github',
      label: 'View on GitHub',
      handle: 'sopt4',
      desc: 'Open source tools, platform code, and public engineering updates.',
      href: 'https://github.com/sopt4',
      action: 'View',
    },
    {
      key: 'youtube',
      label: 'Watch on YouTube',
      handle: '@soptfour-u2c',
      desc: 'Tutorials, walkthroughs, and operator content.',
      href: 'https://www.youtube.com/@soptfour-u2c',
      action: 'Subscribe',
    },
    {
      key: 'whatsapp',
      label: 'Join on WhatsApp',
      handle: 'QYVORA Community',
      desc: 'Live sessions, announcements, and operator comms.',
      href: 'https://chat.whatsapp.com/Ja8pR0FZQAI2pceGjQpji5',
      action: 'Join',
    },
  ],
  nav: {
    groups: [
      {
        key: 'learn',
        label: 'Learn',
        items: [
          { key: 'courses', label: 'Courses', path: '/courses', desc: 'Self-paced courses' },
          { key: 'hpb', label: 'HPB', path: '/hpb', desc: 'Hacker Protocol Bootcamp' },
          { key: 'events', label: 'Events', path: '/events', desc: 'Live events' },
          { key: 'services', label: 'Services', path: '/services', desc: 'Pentesting services' },
        ],
      },
      {
        key: 'research',
        label: 'Research',
        items: [
          { key: 'anansi', label: 'Anansi', path: '/anansi', desc: 'Attack Surface Intelligence' },
          { key: 'quiteroot', label: 'QuiteRoot', path: '/quiteroot', desc: 'Offensive research and engineering' },
          { key: 'market', label: 'Market', path: '/zero-day-market', desc: 'Zero-day intelligence vault' },
        ],
      },
      {
        key: 'resources',
        label: 'Resources',
        items: [
          { key: 'blogs', label: 'Blogs', path: '/blogs', desc: 'Read our blog' },
          { key: 'news', label: 'News', path: '/news', desc: 'Cyber threat feed' },
          { key: 'leaderboard', label: 'Leaderboard', path: '/leaderboard', desc: 'Top operators ranking' },
        ],
      },
      {
        key: 'company',
        label: 'Company',
        items: [
          { key: 'team', label: 'Team', path: '/team', desc: 'Meet the team' },
      { key: 'contact', label: 'Contact', path: '/contact', desc: 'Get in touch' },
      { key: 'services', label: 'Services', path: '/services', desc: 'Pentesting services' },
    ],
  },
    ],
    platform: [
      { key: 'events', label: 'Events', path: '/events', desc: 'Live events' },
      { key: 'courses', label: 'Courses', path: '/courses', desc: 'Self-paced courses' },
      { key: 'hpb', label: 'HPB', path: '/hpb', desc: 'Hacker Protocol Bootcamp' },
      { key: 'anansi', label: 'Anansi', path: '/anansi', desc: 'Attack Surface Intelligence' },
      { key: 'quiteroot', label: 'QuiteRoot', path: '/quiteroot', desc: 'Offensive research and engineering' },
      { key: 'blogs', label: 'Blogs', path: '/blogs', desc: 'Read our blog' },
      { key: 'news', label: 'News', path: '/news', desc: 'Cyber threat feed' },
      { key: 'team', label: 'Team', path: '/team', desc: 'Meet the team' },
      { key: 'market', label: 'Market', path: '/zero-day-market', desc: 'Zero-day intelligence vault' },
      { key: 'leaderboard', label: 'Leaderboard', path: '/leaderboard', desc: 'Top operators ranking' },
      { key: 'contact', label: 'Contact', path: '/contact', desc: 'Get in touch' },
    ],
    company: [
      { key: 'team', label: 'Team', path: '/team', desc: 'Meet the team' },
      { key: 'hpb', label: 'HPB', path: '/hpb', desc: 'Bootcamp phases' },
      { key: 'anansi', label: 'Anansi', path: '/anansi', desc: 'Attack Surface Intelligence' },
      { key: 'news', label: 'News', path: '/news', desc: 'Cyber threat feed' },
      { key: 'blogs', label: 'Blogs', path: '/blogs', desc: 'Read our blog' },
      { key: 'contact', label: 'Contact', path: '/contact', desc: 'Open secure contact modal' }
    ],
  },
  
  footer: {
    links: [
      { label: 'Terms of Service', path: '/terms' },
      { label: 'Cyber Feed', path: '/news' },
      { label: 'Anansi', path: '/anansi' },
      { label: 'Learn', path: '/learn' },
      { label: 'Market', path: '/zero-day-market' },
      { label: 'Blogs', path: '/blogs' },
      { label: 'Team', path: '/team' },
      { label: 'Leaderboard', path: '/leaderboard' },
      { label: 'Services', path: '/services' }
    ],
  },
} as const;
